exports.Store = {
    store_id: String,
    store_name: String,
    store_type: String,
    billing_address: String,
    shipping_address: String,
    area_id: String,
    city_id: String,
    state_id: String,
    country_id: String,
    pincode : String,
    latitude: String,
    longitude: String,
    email: String,
    mobilenumber: String,
    contactperson: String,
    tin: String,
    gst: String,
    logo: String,
    banner : String,
    business_days_hours : String,
    delivery_days_hours : String,
    company_id: String,
    status: Boolean,
    created_on: Date,
    created_by: String,
    modified_on: Date,
    modified_by: String
}