/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:70e15111-8865-450d-8bc3-4df6c92d6334",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_RsQecbeJo",
    "aws_user_pools_web_client_id": "sf109f853n4lh3sjq6nhv4rqd",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "groids",
            "endpoint": "https://z2j43cnhu5.execute-api.us-east-2.amazonaws.com/dev",
            "region": "us-east-2"
        },
        {
            "name": "api",
            "endpoint": "https://qzvkkrr9mi.execute-api.us-east-2.amazonaws.com/dev",
            "region": "us-east-2"
        }
    ]
};


export default awsmobile;
